### ISSUE TITLE
Use a machine-readable format for the list

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/static-analysis#194]
Validating the list entries and adding new tools could be easier by using a proper data-exchange format like `YAML` for storing all entries.

The way I imagine this to work is that we have a `data.yml` file, which contains all linters.

```yaml
- name: My Linter
  url: https://www.example.com
  proprietary: True
  description: Static code analysis for C and PHP code.
  lints: ["php", "containers", "packages"]
  type: "tool"
```
The lints could be any programming language or category we have in the `README.md` right now.
The type can be any of `tool`, `webservice`, or `collection`.

This would be rendered into the human-readable format from the `README.md` that we have right now.

**Required steps:**

- [ ] Think about edge-cases where the above format wouldn't work
- [ ] Agree on format
- [ ] Rewrite existing list to `YAML`
- [ ] Rewrite parser for tools located in `/ci` folder
- [ ] Update Travis CI to render the YAML file as a human readable `README.md` and push to master.
- [ ] Update [`CONTRIBUTING.md`](https://github.com/mre/awesome-static-analysis/blob/master/CONTRIBUTING.md)
- [ ] Create a pull request with these changes.

This is quite a big change, but I think it's worth it, because it will make contributing and testing the tools much easier. Also it paves the way for providing different ways for using the list, such as through an API, as a Website with different categories for tools, or as a tool for suggesting linters to IDEs.
